create database customer_behavior;
use customer_behavior;
select * from customer;

-- what is the total revenue generated by male VS female customers
select gender,sum(purchase_amount) as total_revenue 
from customer 
group by gender
order by total_revenue desc;

-- which customers used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer where discount_applied ='Yes'and purchase_amount>=(
select avg(purchase_amount) from customer
);

-- which are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating),2) as avg_product_rating
from customer
group by item_purchased
order by avg_product_rating desc
limit 5;

-- compare the average purchase amounts between standard and express shipping
select shipping_type,avg(purchase_amount)
from customer
where shipping_type in ('standard','express')
group by shipping_type;

-- do subscribed customers spend more ? compare average spend and total revenue 
-- between subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue desc;

-- which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,round(sum(case when discount_applied = 'Yes'then 1 else 0 end)/count(*)*100,2) as dis_percentage
from customer
group by item_purchased
order by dis_percentage desc
limit 5;

-- segment customers into new,returning, and loyal based on their total
-- number of previous purchases, and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case when previous_purchases = 1 then 'new'
	 when previous_purchases between 2 and 10 then 'returning'
     else 'loyal'
     end as customer_segment from customer)
select customer_segment ,count(*) as no_of_customers
from customer_type
group by customer_segment;

-- what are the top 3 most purchased products within each category
with cte as(
select category,item_purchased as products,count(*) as total_purchases,
rank() over(partition by category order by count(*) desc) as rnk
from customer
group by category,products)
select category,products,total_purchases,rnk from cte 
where rnk <= 3;

-- are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe ?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group 
select age_group,sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc;


     
